ARG IMAGE_REGISTRY_PATH
FROM $IMAGE_REGISTRY_PATH/dspdf-rocky8:latest
WORKDIR /app

COPY package .
RUN /bin/bash -c -l "mv .npmrc ~/. && npm config set strict-ssl false && npm install -g `ls *.tgz`"

EXPOSE 8080

CMD [ "/bin/bash", "-c", "-l", "geofix-runserver -p 8080" ]
